<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.1.0</Version>
    <Authors>ZooterOne</Authors>
    <Description>An autonomous, closed-loop communication system between two independent Large Language Model (LLM) instances.</Description>
    <RepositoryUrl>https://github.com/ZooterOne/AutonomousAIChat</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="Spectre.Console" Version="0.55.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

</Project>
